kind: Service
apiVersion: v1
metadata:
  name: db
  labels:
    name: db-service
    app: voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    app: voting-app