kind: Service
apiVersion: v1
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: voting-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: voting-pod
    app: voting-app